schema_version: 1

context:
  name: aws-c-compression
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/awslabs/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: d8e934da2086bfec41f97a0cff749d926f66ccb90f2052f1d70841916c1bf4d7

build:
  number: 0

requirements:
  build:
    - cmake
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ninja
  host:
    - aws-c-common
  run_exports:
    - ${{ pin_subpackage("aws-c-compression", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libaws-c-compression${SHLIB_EXT}
          - test -f $PREFIX/include/aws/compression/compression.h
      - if: win
        then:
          - if not exist %LIBRARY_INC%\\aws\\compression\\compression.h exit 1
          - if not exist %PREFIX%\\Library\\bin\\aws-c-compression.dll exit 1
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: C99 implementation of huffman encoding/decoding
  homepage: https://github.com/awslabs/aws-c-compression
  repository: https://github.com/awslabs/aws-c-compression

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
